#!/bin/bash


WANDB__SERVICE_WAIT=300 deepspeed train.py \
    --deepspeed ./scripts/zero2.json \
    --model_name_or_path /home/chenguangyao/wzh/workspace/LLMDetProj/huggingface/my_llava-onevision-qwen2-0.5b-ov-2/ \
    --version qwen_1_5 \
    --data_path /home/chenguangyao/wzh/workspace/LLMDetProj/grounding_data/llava_cap/LLaVA-ReCap-558K_tag_box_vg7.jsonl \
    --image_folder /home/chenguangyao/wzh/workspace/LLMDetProj/grounding_data/llava_cap/images/ \
    --vision_tower grounding_dino \
    --vision_tower_weight_path /home/chenguangyao/wzh/workspace/LLMDetProj/LLMDet/work_dirs/iter_34000.pth+/home/chenguangyao/wzh/workspace/LLMDetProj/huggingface/ram_plus/ram_plus_swin_large_14m.pth \
    --mm_projector_type mlp2x_gelu \
    --tune_mm_mlp_adapter True \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end False \
    --mm_use_im_patch_token False \
    --load_ram False \
    --grounding_dino_config /home/chenguangyao/wzh/workspace/LLMDetProj/LLMDet/configs/grounding_dino_convnext-t_pretrain_obj365.py \
    --bert_base_path /home/chenguangyao/wzh/workspace/LLMDetProj/huggingface/bert-base-uncased/ \
    --bf16 False \
    --fp16 True \
    --output_dir ./checkpoints/llava-v1.5-7b-pretrain \
    --num_train_epochs 1 \
    --per_device_train_batch_size 2 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 32 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 1000 \
    --save_total_limit 1 \
    --learning_rate 1e-3 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 False \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --dataloader_num_workers 4 \
    --lazy_preprocess True \
    --report_to wandb
